# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created: Tue Apr 17 11:08:39 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 673)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgBtn1 = QtGui.QPushButton(self.centralwidget)
        self.imgBtn1.setGeometry(QtCore.QRect(20, 10, 151, 27))
        self.imgBtn1.setObjectName("imgBtn1")
        self.imgBtn2 = QtGui.QPushButton(self.centralwidget)
        self.imgBtn2.setGeometry(QtCore.QRect(490, 10, 151, 27))
        self.imgBtn2.setObjectName("imgBtn2")
        self.blendBtn = QtGui.QPushButton(self.centralwidget)
        self.blendBtn.setGeometry(QtCore.QRect(340, 560, 92, 27))
        self.blendBtn.setObjectName("blendBtn")
        self.imgView1 = QtGui.QGraphicsView(self.centralwidget)
        self.imgView1.setGeometry(QtCore.QRect(20, 50, 256, 192))
        self.imgView1.setObjectName("imgView1")
        self.imgView2 = QtGui.QGraphicsView(self.centralwidget)
        self.imgView2.setGeometry(QtCore.QRect(480, 50, 256, 192))
        self.imgView2.setObjectName("imgView2")
        self.blendView = QtGui.QGraphicsView(self.centralwidget)
        self.blendView.setGeometry(QtCore.QRect(260, 320, 256, 192))
        self.blendView.setObjectName("blendView")
        self.alpha_slider = QtGui.QSlider(self.centralwidget)
        self.alpha_slider.setGeometry(QtCore.QRect(100, 280, 561, 20))
        self.alpha_slider.setMaximum(10)
        self.alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.alpha_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.alpha_slider.setTickInterval(1)
        self.alpha_slider.setObjectName("alpha_slider")
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(320, 190, 121, 22))
        self.checkBox.setObjectName("checkBox")
        self.alphaValue = QtGui.QLineEdit(self.centralwidget)
        self.alphaValue.setGeometry(QtCore.QRect(670, 280, 71, 27))
        self.alphaValue.setAlignment(QtCore.Qt.AlignCenter)
        self.alphaValue.setObjectName("alphaValue")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 240, 121, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(580, 240, 101, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 520, 121, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 280, 62, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 300, 62, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(640, 300, 62, 17))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.imgBtn1.setText(QtGui.QApplication.translate("MainWindow", "Load Starting Image", None, QtGui.QApplication.UnicodeUTF8))
        self.imgBtn2.setText(QtGui.QApplication.translate("MainWindow", "Load Ending Image", None, QtGui.QApplication.UnicodeUTF8))
        self.blendBtn.setText(QtGui.QApplication.translate("MainWindow", "Blend", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Show Triangles", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaValue.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Starting Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Ending Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Blending Result", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))

